apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 23.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: rook-ceph
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  project: kubeaid
  sources:
    - repoURL: git@github.com:Obmondo/KubeAid.git
      path: argocd-helm-charts/rook-ceph
      targetRevision: 23.0.0
      helm:
        valueFiles:
          - $values/k8s/kbm/argocd-apps/values-rook-ceph.yaml
    - repoURL: git@github.com:kanha-gupta/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
